export { CourseCard } from './CourseCard'
export { CourseCatalog } from './CourseCatalog'
export { CourseCatalogSkeleton } from './CourseCatalogSkeleton'
export { Hero } from './Hero'
export { Header } from './Header'
export { Footer } from './Footer'
export { LandingCatalogo, LandingContent } from './LandingCatalogo'
export { LandingClientWrapper } from './LandingClientWrapper'
export { EducationSection } from './education-section'
export { WSETSection } from './wset-section'
export { TestimonialsSection } from './testimonials-section'