export { CourseCard } from './course-card'
export { CourseCatalog } from './course-catalog'
export { CourseCatalogSkeleton } from './course-catalog-skeleton'
export { Hero } from './hero'
export { Footer } from './footer'
export { LandingCatalogo, LandingContent } from './landing-catalogo'
export { LandingClientWrapper } from './landing-client-wrapper'
export { EducationSection } from './education-section'
export { WSETSection } from './wset-section'
export { TestimonialsSection } from './testimonials-section'
